# Generated by Django 3.2.5 on 2021-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Enrollment', models.CharField(max_length=15)),
                ('Department', models.CharField(max_length=5)),
                ('Mobile', models.CharField(max_length=10)),
                ('Detail', models.CharField(max_length=500)),
                ('added_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'complaint',
                'verbose_name_plural': 'complaints',
            },
        ),
    ]
