# Generated by Django 3.2.5 on 2021-07-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_complaint_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
