# Generated by Django 3.2.5 on 2021-07-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_complaint_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Email',
            field=models.EmailField(max_length=20, null=True),
        ),
    ]
