# Generated by Django 3.2.5 on 2021-07-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_complaint_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='added_on',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
