# Generated by Django 3.2.5 on 2021-07-15 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ComplaintNumber',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
