# Generated by Django 3.2.5 on 2021-07-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20210715_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'ContactUs', 'verbose_name_plural': 'contactsUs'},
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='ComplaintNumber',
            new_name='complaintnumber',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='Detail',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='Enrollment',
            new_name='enrollment',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Reason',
            new_name='reason',
        ),
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
