# Generated by Django 3.2.5 on 2021-07-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20210715_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='submitted', max_length=20),
        ),
    ]
