# Generated by Django 3.2.5 on 2021-07-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_rename_uploadpicture_complaint_upload_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Complaint Has Been Submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='upload_picture',
            field=models.ImageField(default='images/default', upload_to='portal/images'),
        ),
    ]
