# Generated by Django 3.2.5 on 2021-07-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_alter_complaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='upload_picture',
        ),
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(default='articles/default.jpg', upload_to='img'),
        ),
    ]
