# Generated by Django 3.2.5 on 2021-08-06 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_alter_complaint_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintnumber', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=25)),
                ('enrollment', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=5)),
                ('regarding', models.CharField(choices=[('CLG', 'College'), ('HOS', 'Hostel')], default='CLG', max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('detail', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='articles')),
                ('status', models.CharField(default='Complaint Has Been Submitted.', max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
            },
        ),
    ]
