# Generated by Django 3.2.5 on 2021-08-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_complaints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaints',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images'),
        ),
    ]
