# Generated by Django 3.2.5 on 2021-08-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_rename_photo_img_complaint_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(upload_to='complaint/'),
        ),
    ]
