# Generated by Django 3.2.5 on 2021-08-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_alter_complaint_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('SUB', 'Complaint Has Been Submitted.'), ('PRG', 'Complaint Is Under Progress.'), ('RES', 'Your Complaint Has Been Resolved.')], default='SUB', max_length=100),
        ),
    ]
