# Generated by Django 3.2.5 on 2021-08-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Complaint Has Been Submitted.', 'Complaint Has Been Submitted.'), ('Complaint Is Under Progress.', 'Complaint Is Under Progress.'), ('Your Complaint Has Been Resolved.', 'Your Complaint Has Been Resolved.')], default='Complaint Has Been Submitted.', max_length=100),
        ),
    ]
